server:
  port: 8080

spring:
  profiles:
    active: dev # 실행 서버 지정
  application:
    name: diary-app
jwt:
  secret: ${JWT_SECRET:fl63X7JQkcAeiDobfsMT1hpe3c98nufFwwHILTmtdoeoC6ox33MXp+PoVeKgDdiPGHSAWz/mvatRCOAfghY1Vw==}
  access_token_expiration: 600000 # 10?
  refresh_token_expiration : 259200000 # 3?

kakao:
  client:
    id: ${KAKAO_CLIENT_ID:9b2d6412af07621709962b653139df4e}
    secret: ${KAKAO_CLIENT_SECRET:pPAD4ZZ3u3iU1wluJcexe9Evg0FNIkqu}

feign:
  client:
    config:
      default:
        connectTimeout: 5000 # 3-way-handshake ??? 5??? ???? ??? ????
        readTimeout: 5000 # ??? ??? ??? ?? ?? ??



