spring:
  # 데이터베이스 설정
  datasource:
    url: # AWS
    username: # AWS
    password: # AWS Secreat Manager password 변환 끄기
    driver-class-name: com.mysql.cj.jdbc.Driver
  
  # JPA 설정
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    open-in-view: false


# 로깅 설정
logging:
  level:
    com.cheolhyeon.diary: info

feign:
  client:
    config:
      default:
        connectTimeout: 5000 # 3-way-handshake 과정이 5초내로 이뤄지지 않으면 에러발생
        readTimeout: 5000 # 연결은 됐는데 응답이 오지 않는 경우